from .enums import PlatformRole

PLATFORM_READ = "platform.read"
PLATFORM_MANAGE = "platform.manage"
PLATFORM_AUDIT_READ = "platform.audit.read"
PLATFORM_SETTINGS_READ = "platform.settings.read"
PLATFORM_SETTINGS_MANAGE = "platform.settings.manage"
PLATFORM_HEALTH_READ = "platform.health.read"
PLATFORM_METRICS_READ = "platform.metrics.read"
USERS_READ = "users.read"
USERS_CREATE = "users.create"
USERS_UPDATE = "users.update"
USERS_DISABLE = "users.disable"
USERS_ROLES_MANAGE = "users.roles.manage"
WORKSPACES_READ = "workspaces.read"
WORKSPACES_CREATE = "workspaces.create"
WORKSPACES_UPDATE = "workspaces.update"
WORKSPACES_DELETE = "workspaces.delete"
WORKSPACES_MEMBERS_READ = "workspaces.members.read"
WORKSPACES_MEMBERS_MANAGE = "workspaces.members.manage"
API_KEYS_READ = "api_keys.read"
API_KEYS_CREATE = "api_keys.create"
API_KEYS_REVOKE = "api_keys.revoke"
SIGNALS_READ = "signals.read"
TRADES_READ = "trades.read"
ANALYTICS_READ = "analytics.read"
DELIVERIES_READ = "deliveries.read"
DEAD_LETTERS_READ = "dead_letters.read"
OPERATIONS_READ = "operations.read"
OPERATIONS_RECOVERY_MANAGE = "operations.recovery.manage"
OPERATIONS_DEAD_LETTERS_MANAGE = "operations.dead_letters.manage"

ALL_PERMISSIONS = {
    PLATFORM_READ,
    PLATFORM_MANAGE,
    PLATFORM_AUDIT_READ,
    PLATFORM_SETTINGS_READ,
    PLATFORM_SETTINGS_MANAGE,
    PLATFORM_HEALTH_READ,
    PLATFORM_METRICS_READ,
    USERS_READ,
    USERS_CREATE,
    USERS_UPDATE,
    USERS_DISABLE,
    USERS_ROLES_MANAGE,
    WORKSPACES_READ,
    WORKSPACES_CREATE,
    WORKSPACES_UPDATE,
    WORKSPACES_DELETE,
    WORKSPACES_MEMBERS_READ,
    WORKSPACES_MEMBERS_MANAGE,
    API_KEYS_READ,
    API_KEYS_CREATE,
    API_KEYS_REVOKE,
    SIGNALS_READ,
    TRADES_READ,
    ANALYTICS_READ,
    DELIVERIES_READ,
    DEAD_LETTERS_READ,
    OPERATIONS_READ,
    OPERATIONS_RECOVERY_MANAGE,
    OPERATIONS_DEAD_LETTERS_MANAGE,
}

ROLE_PERMISSIONS: dict[PlatformRole, set[str]] = {
    PlatformRole.PLATFORM_OWNER: set(ALL_PERMISSIONS),
    PlatformRole.PLATFORM_ADMIN: {
        PLATFORM_READ,
        PLATFORM_AUDIT_READ,
        PLATFORM_SETTINGS_READ,
        PLATFORM_HEALTH_READ,
        PLATFORM_METRICS_READ,
        USERS_READ,
        USERS_CREATE,
        USERS_UPDATE,
        USERS_DISABLE,
        USERS_ROLES_MANAGE,
        WORKSPACES_READ,
        WORKSPACES_CREATE,
        WORKSPACES_UPDATE,
        OPERATIONS_READ,
        OPERATIONS_RECOVERY_MANAGE,
    },
    PlatformRole.WORKSPACE_OWNER: {
        WORKSPACES_READ,
        WORKSPACES_UPDATE,
        WORKSPACES_MEMBERS_READ,
        WORKSPACES_MEMBERS_MANAGE,
        API_KEYS_READ,
        API_KEYS_CREATE,
        API_KEYS_REVOKE,
        SIGNALS_READ,
        TRADES_READ,
        ANALYTICS_READ,
        DELIVERIES_READ,
        DEAD_LETTERS_READ,
        OPERATIONS_READ,
        OPERATIONS_RECOVERY_MANAGE,
    },
    PlatformRole.WORKSPACE_ADMIN: {
        WORKSPACES_READ,
        WORKSPACES_MEMBERS_READ,
        WORKSPACES_MEMBERS_MANAGE,
        API_KEYS_READ,
        API_KEYS_CREATE,
        API_KEYS_REVOKE,
        SIGNALS_READ,
        TRADES_READ,
        ANALYTICS_READ,
    },
    PlatformRole.ANALYST: {WORKSPACES_READ, SIGNALS_READ, TRADES_READ, ANALYTICS_READ},
    PlatformRole.TRADER: {WORKSPACES_READ, SIGNALS_READ, TRADES_READ, ANALYTICS_READ, DELIVERIES_READ},
    PlatformRole.VIEWER: {WORKSPACES_READ, SIGNALS_READ, TRADES_READ, ANALYTICS_READ},
    PlatformRole.SERVICE: {SIGNALS_READ, TRADES_READ, ANALYTICS_READ},
}
